# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sv6MVV1Fr9PR_vlQuHDjAWfeazNwve2i
"""

from faker import Faker
import random
from datetime import datetime
import pandas as pd

faker=Faker()
def generate_merchant_profile(num_profiles=1000):
    merchant_profiles = []
    for _ in range(num_profiles):
        profile = {
            # Basic Information
            "merchant_id": f"M{faker.random_int(min=1000000, max=9999999)}",
            "business_name": faker.company(),
            "business_type": random.choice(["Electronics", "Fashion", "Grocery", "Home Appliances"]),
            "registration_date": faker.date_between(start_date="-10y", end_date="today"),

            # Business Details
            "business_model": random.choice(["Online", "Offline", "Hybrid"]),
            "product_category": random.choice(["Mobile", "Clothing", "Furniture", "Kitchen"]),
            "average_ticket_size": round(random.uniform(500, 5000), 2),

            # Registration Details
            "gst_status": random.choice([True, False]),
            "pan_number": f"PAN{faker.random_int(min=1000, max=9999)}",
            "epfo_registered": random.choice([True, False]),

            # Location Details
            "registered_address": faker.address(),
            "city": faker.city(),
            "state": faker.state(),

            # Financial Details
            "reported_revenue": round(random.uniform(1e6, 1e9), 2),
            "employee_count": random.randint(5, 500),
            "bank_account": f"AC{faker.random_int(min=1000000000, max=9999999999)}"
        }
        merchant_profiles.append(profile)
    return merchant_profiles