# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sv6MVV1Fr9PR_vlQuHDjAWfeazNwve2i
"""

def generate_transaction_data(merchant_profiles, num_transactions=1000):
    transactions = []
    for _ in range(num_transactions):
        merchant = random.choice(merchant_profiles)
        is_fraud = random.choices([False, True], weights=[0.8, 0.2])[0]
        transaction = {
            # Basic Transaction Info
            "transaction_id": f"T{faker.random_int(min=1000000, max=9999999)}",
            "merchant_id": merchant["merchant_id"],
            "timestamp": faker.date_time_this_year(),
            "amount": round(random.uniform(100, 5000) if not is_fraud else random.uniform(5000, 20000), 2),

            # Customer Info
            "customer_id": f"C{faker.random_int(min=1000000, max=9999999)}",
            "device_id": f"D{faker.random_int(min=1000, max=9999)}",
            "customer_location": faker.city(),

            # Transaction Details
            "payment_method": random.choice(["Credit Card", "Debit Card", "UPI", "Cash"]),
            "status": random.choice(["completed", "failed", "refunded"]),
            "product_category": merchant["product_category"],
            "platform": random.choice(["Web", "Mobile", "POS"]),

            # Risk Indicators
            "velocity_flag": is_fraud and random.choice([True, False]),
            "amount_flag": is_fraud and random.choice([True, False]),
            "time_flag": is_fraud and random.choice([True, False]),
            "device_flag": is_fraud and random.choice([True, False])
        }
        transactions.append(transaction)
    return transactions

import pandas as pd

# Generate Merchant Profiles
merchants = generate_merchant_profile(num_profiles=1000)
merchants_df = pd.DataFrame(merchants)

# Generate Transactions
transactions = generate_transaction_data(merchants, num_transactions=1000)
transactions_df = pd.DataFrame(transactions)

# Merge DataFrames
combined_df = pd.merge(transactions_df, merchants_df, on="merchant_id", how="left")

# Save to CSV
combined_df.to_csv("combined_merchant_transaction_data.csv", index=False)

print("Combined dataset saved successfully!")