# -*- coding: utf-8 -*-
"""Assignment2 Q2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KZIxmiZr9ptXryRkCZnv0TQoxtuBlPfa
"""

import matplotlib.pyplot as plt
train_errors = train_errors[~np.isnan(train_errors)]
errors = errors[~np.isnan(errors)]

plt.hist(train_errors, bins=50, alpha=0.6, label="Train Errors")
plt.hist(errors, bins=50, alpha=0.6, label="All Data Errors")
plt.axvline(threshold, color='r', linestyle='--', label='Threshold')
plt.legend()
plt.xlabel('Reconstruction Error')
plt.ylabel('Frequency')
plt.title('Reconstruction Error Distribution')
plt.show()